theme: jekyll-theme-minimal
title: Niche breadth dynamics in arid vertebrates
description: Does the niche breadth differ between arid and non-arid tetrapods? Are niche dynamics different in ectotherms and endotherms?

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme